### ISSUE TITLE
Not all projects are transferred

### ISSUE THREAD

**Issue by Uniquark** [mikerourke/transfermyti.me#38] opened 2020-04-26 09:25 UTC
Hi Mike. Thank you for creating this tool. It looks very slick. Unfortunately, it seems to be choking on my Toggl data. I have time entries for seven different people with over 600 clients going back almost five years. I have tried to transfer just my information from Toggl to Clockify twice now with partial success. It seems to have transferred all the clients, but it has only transferred about 680 of the 2,255 projects.

When I ran the first transfer, I naively let it try to do everything, but it only transferred a few hundred projects. Also, while it transferred over 8,000 of my time entries, none of them were connected with projects. I then bulk deleted the time entries and tried to transfer just the remaining projects, no time entries. That is when I got up to 681 projects, but that still only gets me up to mid-2017.

I'm trying again right now, but the tool takes about a day to run the whole process, so I'll be pretty slow in reporting back. Do you have any suggestions on transferring all my data?

**Comment by Uniquark** [comment] 2020-04-27 02:20
Hi Again. Well, it goes faster at night than during the day. I was finally able to import all 2,200 projects. However, I have now discovered a much more severe problem. When I imported a few time entries (just the 114 from April), they were imported correctly, but they did not connect with any of the projects. I now have almost four weeks of time entries, all without a project. What do I need to do to make the import work right?

**Comment by alaceyuk** [comment] 2020-04-27 07:01
I don’t want to step on mikes toes here and I’m sure he will respond in due course but I think the core of your issue ‘might’ be that you have more than 1 user. 

The platform doesn’t work if you have more than 1 user in Toggl.

**Comment by mikerourke** [comment] 2020-04-27 15:21
@Uniquark, unfortunately @penguinmedia91 is correct, you're only able to transfer your own time entries, not other users' time entries. I should probably show that on the first page of the tool. A lot of people have asked for it, so I do plan on adding it. However, it'll take a significant amount of effort to implement. I'd like to start working on it sometime in the next month or two but I'm not sure when I'll have it done by. I can let you know when it's ready.

**Comment by Uniquark** [comment] 2020-04-27 17:48
Thank you both for your information. I have actually had some success since I last posted to this thread. As I mentioned before, running the tool over and over eventually transferred all my project entries. The next error seems to have been solved by switching from Safari to Chrome. Chrome seems to correctly import all my time entries with the proper connections to the projects. Of course, I have not examined each one, but they look good at first blush. Interestingly, the transfer tool seems to run marginally more quickly on Chrome than it did on Safari. It still takes hours, but not quite as many.

  I then tried transferring my wife's time entries and they came through without a hitch. In fact, it copied over 7,000 entries in one half-hour transfer. I wonder if Chrome would have been able to transfer all the projects in one go. I'm not sure about that because my first try with Safari did transfer 8,000 time entries (without the project connections).

  Then I tried transferring my son's time entries and ran into another issue. The tool gathers all his entries, but it clearly indicates that there are no projects associated with them at the record-selection screen. This did not happen with my wife's transfer, so there must be some difference between her account and his account. My first guess is that she is an admin and he is not. I will have to try changing his account, but I have other issues to deal with for the next few days. This project will have to wait until I have some more time to play with it.

Thank you for your help.

**Comment by mikerourke** [comment] 2020-04-27 18:25
I'm glad to hear it worked (sort of) and frankly, I'm surprised that the tool was able to handle the sheer volume of data. I erred on the side of caution on the rate limit accommodations, which is why it takes so long. I wonder if your IP address got flagged on Clockify's servers :).

Let me know if there's anything else I can help with. I'll keep this issue open for now because it's related to the multi-user workflow. If I close it, it will officially be wiped from my memory.

**Comment by Uniquark** [comment] 2020-04-27 18:37
Thanks for the followup, Mike. I'll post an update when I get back to this project.

I don't mind the time it takes. I like that I can just set it running and come back to it sometime later to see how it is going. For what it's worth, it would be nice to have a bit more progress indication. The actually transfer process is very nice with the count completed and total to transfer and the thermometer, but the fetching process just sits unchanged for the entire time. The only indication of progress is when it changes from "projects" to "tasks" to "time entires" (or whatever it says). Interestingly, in Chrome, I get the cutesy graphic of the tiles unfolding. In contrast, Safari just shows a solid diamond for the entire process.

**Comment by Uniquark** [comment] 2020-05-03 01:53
Ok, I'm back. The tool definitely handles the volume of data just fine, as long as I use Chrome. I have not gone back to Safari since I discovered that difference. It also definitely can handle more than one user for a workspace: It transferred both my and my wife's times just fine. However, I have not been able to get it to transfer my granddaughter's time entries. Each time I ask it to fetch her entries, it grabs them all (she has only a few thousand), but it grabs no projects at all. Do you have any ideas on why this would happen?

  When i originally set up the Toggl workspace, I was the "owner" of the space and my wife was an "admin." About two years later, I added my granddaughter, but I failed to set her up as an admin. That is the only difference I can find between my wife's account and her account, but I have now set my granddaughter as an admin and I still don't get the projects connected to her time entries.

  I tried quarrying her Toggl account for time entries using curl and I received project IDs for each time entry. I also tried quarrying her Toggle account for project entries without and trouble.

**Comment by mikerourke** [comment] 2020-05-05 18:32
Hi @Uniquark, I apologize for the delayed response. I would imagine if you're using the API key associated with your granddaughter's account, you should see her projects. I suspect the issue is related to having multiple users/admins, but I won't know more until I start adding the multi-user transfer feature. At this point, I can just speculate. I'll update the issue when I know more.

**Comment by Uniquark** [comment] 2020-05-05 19:15
Hi Mike. I understand about delayed responses. I actually love asynchronous communication. It lets me work when I'm ready and other work when they are ready. I look forward to hearing when you have added multiuser transfers. For now, I am at a dead end. I have no other ideas on how to get those times transferred, so we will just get by without them. Fortunately, I was able to transfer the important information. If we need additional reports on past work, I'll just go back to my Toggl account.

**Comment by gravytrainhub** [comment] 2021-04-19 14:19
@mikerourke could you have a look at this 6 seconds video: https://drive.google.com/file/d/1itVwhb8m2OVW1Ng9pk5ts9GVdxEjsY7V/view?usp=sharing

It stops after few projects (this is from my toggl account to my clockify account). What to do?

**Comment by mikerourke** [comment] 2021-04-19 15:50
@gravytrainhub It's hard to diagnose the issue just from seeing `400` errors. I can try testing it out on my end to see if anything has changed in either tool.

Could you please answer the following questions to narrow down my troubleshooting?
1. Are you trying to transfer data from a multi-user account, or is it a personal account with a single user?
2. Do you have any time entries that aren't associated with a project?
3. Did you create the workspace(s) on Clockify _before_ attempting the transfer?
4. If so, does the Toggl workspace name match the Clockify workspace name?

**Comment by gravytrainhub** [comment] 2021-04-29 06:30
Tnx for your answer, Sorry I did only see it after 10 days..

1. My account is the 'superadmin' of multiple users (in a multiple-user business account), but I only transfer from my own personal account with my own API token.
2. no
3. yes
4. yes

I have managed to transfer almost everything in multiple sessions, but a few 100 entries still don't transfer. Maybe your server has limits as to how many could be handled in terms of array depth? Or length? (limits?).
Because I have lots of projects and time entries...

**Comment by gravytrainhub** [comment] 2021-04-29 06:42
@mikerourke I tried again after removing every cookie or local data I could find from your transfermyti.me website. And it worked. The last remaining 313 entries where transfered succesfully.

**Comment by mikerourke** [comment] 2021-04-29 16:46
@gravytrainhub That's good to hear! I'm not running any server (the app is just grabbing data from Toggl and making API requests to Clockify), so I suspect Clockify's servers can't keep up with a high volume of updates. I'm glad you were able to transfer the rest of your data. Let me know if you have any more issues or questions.

**Closed as completed** 2022-02-18 16:32 UTC
Labels: bug
